IATI/IATI-Standard-Website

- README.md
- iati/requirements-dev.txt
- pytest.ini
Adds pytest as a basis for project tests.
> Add pytest infrastructure

- README.md
Fixes a filepath in the install instructions.
> Fix command in setup instructions

- README.md
Adds these commands to the README, since they are needed to run code from this branch.
> Add additional setup commands

- iati/iati/settings/base.py
Solving issue https://github.com/IATI/preview-website/issues/60
> From en-gb to just en

- iati/iati/templates/base.html
Add a link to Twitter, with `target="_blank"` to open in a new website, and `rel="noopener noreferrer"` to prevent phishing attacks in the future.
> Twitter link, but we don't have a Facebook or a LinkedIn?

- iati/iati/templates/404-static.html
- iati/iati/templates/404.html
- iati/iati/templates/500-static.html
- iati/iati/templates/500.html
- iati/iati/templates/error-base.html
Some of this work was done and already merged into `dev` but evidently not merged downstream. Replicating it here in a hurry for the Alpha.
> Static and dynamic error pages for wagtail and apache2

- iati/about/templates/about/about_page.html
- iati/about/templates/about/about_sub_page.html
- iati/about/templates/about/case_study_index_page.html
- iati/about/templates/about/case_study_page.html
- iati/about/templates/about/history_page.html
- iati/about/templates/about/people_page.html
Boolean to check for excerpt, and apply bottom margin if none.
> No none excerpt

- iati/about/templates/about/case_study_index_page.html
Fixes missing link for case study titles on index page
> Fix index link

- iati/tests/about_functional_tests.py
- iati/tests/base_functional_tests.py
- iati/tests/contact_functional_tests.py
- iati/tests/events_functional_tests.py
- iati/tests/home_functional_tests.py
- iati/tests/news_functional_tests.py
- iati/tests/support_functional_tests.py
Creates functional test files into the structure agreed internally.
> Setup functional test files

- .gitignore
- iati/tests/base_functional_tests.py
- iati/tests/data/strings.py
- iati/tests/functional_tests.py
Scope of this one changed. Content creation checks need to be made by their respective app functional tests so testing every field not going to happen here afterall.
> Fixes some linting errors and adds basic default page test

- iati/home/management/commands/createdefaultpages.py
- iati/tests/base_functional_tests.py
@allthatilk Went ahead and wrote this refactor, but waiting on https://github.com/IATI/preview-website/pull/105 to be merged before adding testing.
> Refactor createdefaultpages

- iati/tests/about_functional_tests.py
Fix for tests to ensure the right browser window is being checked for changes.
> Refactor to make sure admin CMS window closes, update docstring

- iati/tests/functional_tests.py
See: https://github.com/cobrateam/splinter/issues/609
> Remove test that throws Splinter error

- iati/guidance_and_support/models.py
- iati/guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
- iati/guidance_and_support/templates/guidance_and_support/guidance_index_page.html
- iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
- iati/guidance_and_support/translation.py
- iati/iati/templates/base.html
Branching from alpha but adding in guidance models.
> Guidance models alpha

- README.md
Resolves a couple errors in the paths for setup commands following a run through of the fresh install of the project.
> Fix setup commands in README

- iati/iati/templates/base.html
Changes made on advice about what is needed to ensure compliance with new GDPR regulations.
> Add link to current Privacy Policy

- iati/news/templates/news/news_index_page.html
Only highlight the first article on the first page.
> Featured only on page 1

- iati/events/models.py
- iati/tests/events_functional_tests.py
For event start to help with making migrations
> Default date

- iati/events/templates/events/event_page.html
- iati/home/management/commands/importnews.py
- iati/home/templatetags/iati_tags.py
- news.json
Changing the classes were specified by Rohini. Also wanted to make it so events don't display "midnight"...
> Update news/event classes as specified by Rohini

- iati/tests/iati_standard_functional_tests.py
Tiny PR, just adds a test and updates some test docstrings.
> Add test for editable header image

- iati/tests/about_functional_tests.py
- iati/tests/base_functional_tests.py
- iati/tests/events_functional_tests.py
- iati/tests/home_functional_tests.py
- iati/tests/iati_standard_functional_tests.py
- iati/tests/news_functional_tests.py
- iati/tests/using_data_functional_tests.py
Just trying to fix the random failures.
> Fix header flake

- iati/tests/using_data_functional_tests.py
Because they keep breaking on the merge build Travis tests.
> Remove mostly header tests

- iati/iati/templates/base.html
with anonymize_ip for GDPR reasons.
> Gtag script for iatistandard property

- .travis.yml
Adding `sudo: required` on .travis.yml to see how that affects performance.
> sudo travis

- iati/about/templates/about/case_study_index_page.html
- iati/about/templates/about/people_page.html
- iati/events/templates/events/event_index_page.html
- iati/guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
- iati/guidance_and_support/templates/guidance_and_support/knowledgebase_page.html
- iati/home/templates/home/home_page.html
- iati/iati/templates/base.html
- iati/news/templates/news/news_index_page.html
- iati/news/templates/news/news_page.html
With links to styles.iatistandard.org
> Complete replacement of static assets

- iati/home/templates/home/home_page.html
- iati/iati/templates/base.html
Fix Getting Started section so links work.
Update menu item for Using Data
Update video link to match on-brand video.
> Fix homepage links

- iati/home/templates/home/home_page.html
Update video link to updated video with iatistandard.org URL at the end.
> Update iati video on the homepage

- .pylintrc
- .travis.yml
- iati/contact/models.py
- iati/events/models.py
- iati/events/translation.py
- iati/guidance_and_support/models.py
- iati/home/management/commands/importnews.py
- iati/home/management/commands/updatestatistics.py
- iati/home/templatetags/iati_tags.py
- iati/home/wagtail_hooks.py
- iati/iati/activate_languages.py
- iati/iati/urls.py
- iati/iati_standard/models.py
- iati/news/models.py
- iati/news/translation.py
- iati/tests/home_functional_tests.py
- iati/using_data/translation.py
Continuing work from #199…
I’ll just keep adding to this one until I get super bored.
> [COMPLETE] More linting fixes

- iati/home/models.py
See https://github.com/IATI/preview-website/pull/205#issuecomment-405285018
> Ignore invalid charblock variable name

- iati/iati/templates/base.html
> Remove foot comment containing emails

- iati/iati/urls.py
- iati/iati_standard/templates/iati_standard/iati_standard_page.html
> Fix broken redirects (currently returning a server error)

- iati/home/management/commands/replacelinks.py
> Dev didn't like leading slash

- iati/events/templates/events/event_page.html
To solve mystery IE rendering problems
> Add two missing closing divs

- iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
- iati/guidance_and_support/templates/guidance_and_support/knowledgebase_index_page.html
- iati/guidance_and_support/templates/guidance_and_support/knowledgebase_page.html
- iati/using_data/templates/using_data/tools_index_page.html
So we can skiplink to the toolbox.
> Toolbox id

- iati/home/templates/home/home_page.html
Remove link for activity files to d-portal, awaiting revision from comms before adding again
> Hotfix for activity link on homepage

- iati/requirements.txt
Addresses a reported vulnerability issue https://github.com/IATI/IATI-Standard-Website/network/dependencies
> Django version upgraded from 2.0.5 to 2.0.8

- .travis.yml
- Makefile
- iati/requirements_dev.txt
- iati/tests/home_functional_tests.py
- pytest.ini
- Updated some requirements
- Updated the Geckodriver (main source of failure, apparently)
- `pytest.mark.skip` two otherwise failing tests that will require investigation
- Incremented the verbosity of pytest
> Fix Travis' current state

- iati/guidance_and_support/models.py
- iati/guidance_and_support/templates/guidance_and_support/community_page.html
- iati/guidance_and_support/translation.py
- iati/guidance_and_support/views.py
- iati/home/management/commands/createdefaultpages.py
- iati/home/templates/home/includes/hero_heading.html
- iati/home/templatetags/iati_tags.py
- iati/iati/templates/base.html
Addressing issue #323, adding a community page to the guidance models.
> Adding community page

- iati/iati/templates/base.html
As part of issue #326, Adding Google Tag Manager to the website
> Adding Google tag manager scripts

- iati/iati/custom_middleware.py
Trying to make sure the middleware deals with lowercased urls and documents properly
> Middlewares fixes

- iati/guidance_and_support/templates/guidance_and_support/guidance_group_page.html
- iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
- iati/using_data/templates/using_data/using_data_page.html
This can be seen when used in conjunction with https://github.com/IATI/IATI-Pattern-Library/issues/102
> Adding card paragraph with text pre truncated

- iati/home/templates/home/includes/pagination_links.html
To fix the vertical pagination link issue.
Deployed branch to staging for review: http://staging.website.iatistandard.org/en/news/?page=2
> Amending markup for list items in pagination

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- iati/templates/base.html
> Add scheme to instances of `request.site.hostname`

- iati/templates/base.html
> Full path to metadata images

- home/models.py
Addresses the issue raised in https://github.com/IATI/IATI-Standard-Website/issues/353#issuecomment-529900203.
> Set min dimensions of social images to 300x300px

- modeltranslation_sync/management/commands/load_trans_nav.py
- modeltranslation_sync/management/commands/save_trans_nav.py
> Save and load translation commands for meganav

- navigation/static/navigation/js/navigation-helpers.js
- navigation/static/navigation/js/navigation-info.js
Incorrect JS conditional now fixed.
> Fixes issue with navigation js additions in incorrect edit screens

- about/templates/about/case_study_index_page.html
- events/templates/events/event_index_page.html
- guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
- guidance_and_support/templates/guidance_and_support/guidance_group_page.html
- guidance_and_support/templates/guidance_and_support/guidance_page.html
- home/templates/home/home_page.html
- home/templates/home/includes/breadcrumbs.html
- home/templates/home/includes/featured_event.html
- home/templates/home/includes/sibling_links.html
- home/templates/home/includes/sidepanel.html
- home/templatetags/iati_tags.py
- news/templates/news/news_index_page.html
- news/templates/news/news_page.html
- tools/templates/tools/tool_listing.html
- using_data/templates/using_data/using_data_page.html
Requires some user-testing before merge.
> slugurl_trans to pageurl

- README.md
- docker-compose.yml
- home/templates/home/includes/hero_feed_image.html
- iati/settings/production.py
This PR enhances the logic for displaying the "Past Event" badge on the events Hero.
- Currently, once the "Start Date" has passed the the Badge shows as "Past Event". This can be confusing for long events like the MA
- the code was only checking if the page.date_start had passed and not taking into account page.date_end
```
{% if page.date_start|haspassed  %}
<span class="badge">{% trans "Past event" %}</span>
{% endif %}
```
Now, the template checks if the "End Date" exists and has passed and if so displays "Past Event"
Then checks if "End Date" exists and the "Start Date" has passed and if so displays "In Progress"
Then if "End Date" does not exist and "Start Date" has passed is displays "Past Event"
> Better logic for ongoing events

- entrypoint.sh
- iati/settings/base.py
Based on advice from these sources:
https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7
https://hackernoon.com/why-you-should-almost-always-choose-sync-gunicorn-over-workers-ze9c32wj
https://www.revsys.com/tidbits/django-performance-simple-things/
> Optimize gunicorn settings and db persistence

- .github/workflows/workflow.yml
- upgrade model translation package
> Next Release

- .github/workflows/workflow.yml
[Trello](https://trello.com/c/ruACmyGf)﻿
> login to dockerhub with iatitechteam account to prevent anonymous pull rate-limiting

- .github/workflows/workflow.yml
[Trello](https://trello.com/c/L9pFidFq)
> Translations 04-02-2022

- README.md
[Trello](https://trello.com/c/XXlIX42L/221-iati-bot-github-pat-is-outdated-format)
> update github PAT to new format

- .github/workflows/workflow.yml
[Trello](https://trello.com/c/jgqxleVf)
> change container registry, use env var

- guidance_and_support/templates/guidance_and_support/support_page.html
This reverts commit 57f5282f7755646b3f6049b0e9e8a5c1e3ea0f2a.
> Revert "Roll back support page for testing"

- about/templates/about/history_page.html
Ticket https://trello.com/c/0Ua1j6LJ/39-fix-the-historypagehtml-template-to-allow-odd-number-of-blocks
>  Add if statement to cater for odd timeline_editor blocks

- search/models.py
> Fix | Duplicate Search

- iati/templates/scaffold/header.html
[Ticket ](https://github.com/IATI/IATI-Standard-Website/issues/710)
> Feature | Header Search Accessibility

- .github/workflows/workflow.yml
https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-10.4.1#new-azvm
> Dev hotfix: Azure makes us specify the version of the Ubuntu VM image now

- .github/workflows/workflow.yml
https://github.com/IATI/IATI-Standard-Website/pull/735 but for live.
> Install prometheus on the live server

- .github/workflows/workflow.yml
https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-10.4.1#new-azvm
> Prod hotfix: Azure makes us specify the version of the Ubuntu VM image now

- Dockerfile
Dev deploy at http://20.254.43.167:5000/en/search/?query=test which seems to work.
> Dockerfile: Update elasticsearch minor version

- iati/templates/partials/social-graph.html
https://github.com/IATI/IATI-Standard-Website/issues/747
> social-graph: Fix og:image and twitter:image

- .github/workflows/workflow.yml
New variable DEV_BRANCH_NAME sets which branch
is deployed on the dev servers.
> github actions: Dev deploys can be any branch, set by variable

- README.md
Change "docker-compose" to "docker compose"
Set correct port to use to look at site
> README.md: update dev notes

- .github/workflows/workflow.yml
https://github.com/IATI/IATI-Standard-Website/issues/777
> Azure VM's with Standard IP's

- .github/workflows/workflow.yml
Once this is merged into develop, I'll rename the current master to main, and create a PR for merging develop into the new main.
> git: Rename master->main to match other IATI repos

- Dockerfile
- config/logrotate.conf
Commit 87764f38cc0f485903a39c762bc6bf81109cd388 removed it by mistake
> Add Gunicorn Logrotate back in

- guidance_and_support/templates/guidance_and_support/includes/contact_form.html
Set the value of the hidden 'referrer' field only if it's empty
> guidance_and_support: contact form

- guidance_and_support/templates/guidance_and_support/guidance_page.html
- guidance_and_support/templates/guidance_and_support/includes/contact_form.html
- guidance_and_support/templates/guidance_and_support/includes/form-item.html
Revisit work in https://github.com/IATI/IATI-Standard-Website/pull/814
> 2026 03 26

- guidance_and_support/templates/guidance_and_support/guidance_page.html
> guidance_and_support: delete contact form at the bottom

- iati/templates/scaffold/header.html
- patterns/converted-html/assets/css/screen.css
> feat: add hint to anyone searching for an org on the site
