- iati/home/models.py
- iati/home/translation.py
- iati/home/translation_helper.py
`fields` attribute gets turned into a dict by Django modeltranslation, so we can't rely on it to predictably order the fields to be translated. I've moved fields from the translation.py into respective models.py's, so the TranslationOptions class can just copy it from there. See events/models.py for an example, but the way I've set this up now each model to be translated will need `translated_fields` array and if you want additional panels the `multilingual_field_panels` also goes in the page models now.
> Can't use fields attribute from TranslationOptions

- README.md
`manage.py makemigrations_translation` and `manage.py migrate_translation` extend default django makemigrations and migrate functionality to include database changes for translated content.
> Remove unnecessary setup commands

- iati/conftest.py
- iati/home/templatetags/iati_tags.py
- iati/iati/settings/base.py
- iati/search/migrations/0001_initial.py
- iati/tests/about_functional_tests.py
- iati/tests/base_functional_tests.py
- iati/tests/functional_tests.py
- pytest.ini
Hey Imogen,
This is as far as I got with the tests. The linchpin change was line 32 of settings/base.py. Importing the migrate function explicitly allows that to work and gets rid of the annoying cursor error.
Once I got that working, I realized that we cannot just open a server separately and then change to a testing database. You have to open the server after switching to the testing database, which is why admin_browser inherits from `live_server`. There's a tiny bit of documentation on it here: http://pytest-django.readthedocs.io/en/latest/helpers.html But it's super cool and runs the django server for you.
And unfortunately this also runs us into a long-standing and unsolved wagtail bug here: https://github.com/wagtail/wagtail/issues/1824 If we want the DB changes to be transactional, …
> Test about sub page live server

- iati/tests/about_functional_tests.py
Complete test setup
Refactor module helper functions
Refactor TestAboutChildPageCreation to incorporate module helper functions
Refactor TestAboutChildPageCreationt to better specify CSS elements by xpath
Found xpath that only returns one result for adding a child page to the Case Studies Index page in order to avoid having to rely on an arbitrary index position in a list of results
Complete test to check the created Case Study page is available in the website
Only checks case study pages are created, will keep these changes self-contained and create a new branch for other CMS tests for pages using the About app models.
> Test case study children

- .travis.yml
- pytest.ini
This prevents the need to set DJANGO_SETTINGS_MODULE as an environment variable. In doing so, this makes the code more portable.
> Set DJANGO_SETTINGS_MODULE in pytest settings

- iati/requirements.txt
Change made following issues with dev machines (and travis) being on different versions.
Version numbers have been taken from latest passing Travis build.
Will look at if it is possible to pin `django-modeltranslation` in a seperate PR.
> Pins dependcies to specific versions

- iati/requirements.txt
Downloads from a pinned version on pip for consistency with other dependencies. Additionally pining to this version reduces the chance of breaking changes causing dev/travis build issues.
> Download django-modeltranslation==0.13b1 from pip

- iati/home/models.py
- iati/home/templates/home/includes/hero_heading.html
- iati/home/translation.py
- iati/tests/home_functional_tests.py
Got some functional replication but I think that should get fixed in a different scope as we need to consolidate and refactor a bunch of our existing tests anyway.
> Editable home header text

- iati/tests/conftest.py
This slows down the admin browser by 0.1 second so elements that fade in and out can be fully loaded before Selenium tries to click on them. Should resolve any issues with tests that are failing as an element is not yet visible/clickable/obscured-by-fade effects/etc.
> Slow down admin browser

- iati/home/templates/home/includes/streamfield.html
One single typo on the doc url.
> Doc box hotfix

- iati/home/models.py
- iati/home/templates/home/standard_page.html
- iati/home/templatetags/iati_tags.py
- iati/home/translation.py
- iati/iati/templates/base.html
- iati/tests/events_functional_tests.py
- iati/tests/home_functional_tests.py
Standard page template, abstract content page model with `fixed_page_type` choice field anticipating two special uses of this page for the `privacy page` and the `terms and conditions page`. Re-usable otherwise.
> Standard page models

- iati/home/models.py
- iati/home/templates/home/home_page.html
- iati/tests/about_functional_tests.py
A few short changes so case studies do not appear on the HomePage until there are case studies in the DB. Slightly tricky because I had to avoid a circular import from Home.models and About.models, but otherwise pretty straight forward.
Added test in about page models that checks to see if the case study section appears on the home page after publishing a case study page.
> Working case study query and filter

- iati/iati/urls.py
- iati/tests/base_functional_tests.py
- iati/tests/conftest.py
- iati/tests/events_functional_tests.py
- iati/tests/home_functional_tests.py
- iati/tests/news_functional_tests.py
Made admin URL a single variable in `iati/urls.py` and imported it in every place it's used in tests. This way, if we choose to change it again later the update will be easier. For now set to `cms` and thus `django-cms`
> Flexible admin url

- iati/home/views.py
- iati/iati/urls.py
Captures all urls that begin with a version number and redirects them to reference.iatistandard.org
> Reference redirect

- iati/about/templates/about/about_sub_page.html
- iati/about/templates/about/case_study_index_page.html
- iati/about/templates/about/case_study_page.html
- iati/about/templates/about/history_page.html
- iati/about/templates/about/people_page.html
- iati/home/templates/home/home_page.html
- iati/home/templates/home/includes/hero_heading.html
Stops 'None' appearing in the header when no excerpt is provided via the CMS.
> Remove excerpt placeholder

- iati/home/templates/home/home_page.html
I guess as good practice (and presumably for internationalisation) these should use template tags rather than hard-coding.
(NB I’ve not tested this at all; I haven’t even cloned the repo.)
> Replace hard-coded URLs in home template

- iati/home/management/commands/updatestatistics.py
API query was not counting publishers without activities before.
> All publishers fix

- iati/requirements_dev.txt
This stops pylint complaining about some dynamic methods on `BaseCommand.style` e.g. here:
https://github.com/IATI/preview-website/blob/38d0107927e94cc435101dae320dcdf09988ba21/iati/home/management/commands/importnews.py#L46
> Upgrade pylint-django (and pylint)

- .travis.yml
Just a bit of tidying up.
This is leftover from testing linting on add-page-models. That branch is
gone now, so this doesn’t need to be here anymore.
> Remove mention of add-page-models from travis.yml

- .travis.yml
Make travis do linting before running tests.
Tests are super slow (#224) so it really sucks when they finish successfully and then linting fails.
In such cases, it makes more sense to Fail Fast™ and don’t bother testing if linting fails.
> Lint first!!! Ask questions later!!!

- README.md
Following the repo renaming, the Travis badge has been updated as well (thanks @andylolz for pointing that one out as well!)
> Update travis badge following repo renaming

- iati/home/models.py
- iati/tests/management_unit_tests.py
Overriding the clean method to strip any leading and trailing dashes on slugs, fixing an issue where trailing dashes were added to the automatically generated slugs if there was a whitespace after the title name
> Fix slug trailing dash

- iati/events/tests/test_events_models.py
- iati/home/tests/test_middleware.py
- iati/iati/custom_middleware.py
- iati/iati/settings/base.py
Redirects to reference.iatistandard.org should not be lowercased.
Fixes #332.
> Reorder middleware

- iati/home/templatetags/iati_tags.py
- iati/iati/settings/base.py
Adding to work completed for #329.
- Adds a fallback URL for the Community page. When the site is deployed, the Discuss URL will be linked to from the Community menu item until the new Community page is made live. 
I see this as temporary, but essential!
> Adding fallback for community page

- iati/iati/settings/dev.py
- iati/iati/templates/partials/social-share.html
As per #347 , `{{ request.scheme }}` has been added if not in `debug` mode
Having the protocol prepended when we're dev-ing locally doesn't make much of a difference to be completely honest, but decided to do it proper and exclude it anyway
> Facebook share button doesn’t work

- events/models.py
- events/tests/test_events_models.py
Addressing #368 
`get_context` for past events now checks the end date instead of the start date for filters.
> Switch date_start for date_end when filtering past events. 

- events/models.py
- events/tests/test_events_models.py
Current event: `end_date__lte = now`
Past event: `end_date__gt = now`
An event still running/ending today is a current event; any event that ended days prior to today are past.
> Correct when an event is marked as past

- events/models.py
- events/tests/test_events_models.py
Just adds a check to `datetime.min.time()` to make sure we know when an event is in the past (`ends before 00:00am of Today's date`)
> Small hotfix so that the events won't disappear

- .pylintrc
- .travis.yml
- Makefile
- __init__.py
- requirements_dev.txt
pylint was removed in 44fe88a992b54d212d4c243cbf84f79f5947cf26 (possibly by accident, since it’s a really big commit).
This adds it back.
This PR includes two more improvements:
* cache pip (to speed up the build process)
* change branch name in travis (it looks like `dev` was renamed `develop`)
> Re-add pylint as an automated testing step

- about/templates/about/case_study_index_page.html
A reference to load static and the basic.css file was in the case study index template by mistake, this has been removed.
> Remove rogue static reference in case study index template

- home/management/commands/redirectpage.py
Works as such:
```
$ docker-compose exec web python3 manage.py redirectpage 555 655
Replacing soft-link in page: How do I use IATI data?
Replacing soft-link in page: Using the CSV Query Builder
Replacing soft-link in page: Using the CSV Query Builder
Replacing soft-link in page: Using the CSV Query Builder
Replacing soft-link in page: Using the CSV Query Builder
Successfully replaced 555 with 655
```
> Redirect page command

- home/templates/home/modules/iati-tools.html
Adds a conditional to the home page tools module so that the logo module is only displayed if the selected tool has a logo present.
> Add conditional to home tool logo element

- tools/models.py
To address https://trello.com/c/D5XrDBjd/114-add-child-pages-to-the-iati-guidance-site
> Allow sub-sub tools pages

- modeltranslation_sync/management/commands/save_trans.py
Previously we would not blank out the translated string for StreamValue objects that had changed English, which led to the translators not re-translating these changed fields.
Note from translator
```
The sentence "See more information about the service in the product sheet" does not have an updated French translation 
because in the .po file we received it was paired with the existing French translation "Pour en savoir plus sur le service et 
ses tarifs, cliquez ici". As such, the updated English sentence was not imported into our translation tool because this 
imports only unpaired English sentences in the .po file without an existing French translation. As a result, no updated 
French translation for the sentence "See more information about the service in the product sheet" was …
```
> blank out translated string in .po for StreamValue objects with changes

- iati/settings/base.py
With:
3813, 4002, 3772 (avg 3862.3 ms response)
Without:
4768, 4335, 4261 (avg 4454.6 ms response)
Average of 592 ms saved
> Cache image renditions

- iati/custom_middleware.py
> Feature | Reference Homepage redirect

- Dockerfile
- delete_large_logs
PR for develop, the same as is already on master: https://github.com/IATI/IATI-Standard-Website/pull/724
> Hotfix | Delete gunicorn logs >10G to avoid running out of disk space

- config/nginx/website_dev.conf
- config/nginx/website_prod.conf
This is so that we have a fixed IP to give to the prometheus server.
> Proxy the prometheus port

- .github/workflows/workflow.yml
Hopefully this avoids breakages like the one this morning, where it clobbered the currently live VM.
> deploy: Exit if blue and green resource groups already exist

- iati/settings/base.py
Ensure that REFERENCE_DOWNLOAD_ROOT is within the media dir, or does not begin with a slash.
> settings: Avoid security warnings for reference downloads

- .github/workflows/workflow.yml
- guidance_and_support/templates/guidance_and_support/guidance_page.html
After adding the `referrer` hidden field in the [contact form](https://iatistandard.org/en/guidance/get-support/), the `contact form` at the bottom of [how to publish data](https://iatistandard.org/en/guidance/publishing-data/publishing-checklist/) was like this:
Now it looks like this:
I have also updated `checkout` and `cache` of github's workflow to v3.
> guidance_and_support: templates: guidance_page.html: wrap the form in a form tag
